#! /bin/bash

get-pkg() {
	[[ -z "${ver}" ]] && _fail "Wrong version! Skipping." && return
	[[ -z "${app}" ]] && _fail "Application not found!" && exit 1

	target=`grep "${app} ${ver}" "$_DB" | awk '{ print $3 }'`
	file="${app}-${ver}.nx"
	echo "Downloading $file ..."
	wget -q -nv --show-progress "$target" -O "$_APPS_DIR/$file"
	chmod a+x "$_APPS_DIR/$file"

	if [[ ! `grep "$app $ver" "$_APPS"` ]]; then
		echo "$file $app $ver $target" >> "$_APPS"
	fi
}

[ -z "$1" ] && _help

for pkg in "$@"; do
	_app=($(awk "/$pkg/ { print \$1;}" "$_DB"))
	_ver=($(awk "/$pkg/ { print \$2;}" "$_DB"))

	if [[ "${#_app[@]}" -gt 1 ]]; then
		_echo "\nType wich version(s) of $pkg you want to install separated by spaces:\n"
		for (( c=0; c<${#_ver[@]}; c++ )); do
			_echo "[$c] ${_ver[$c]}"
		done

		read -p " :: " -a vers

		for a in "${vers[@]}"; do
			app="$_app"
			ver="${_ver[$a]}"
			get-pkg
		done
	else
		app="${_app}"
		ver="${_ver}"
		get-pkg
	fi
done

_echo "Done installing apps."
