#! /bin/bash

[ -z "$1" ] && _help

delete-pkg() {
	rm "$_APPS_DIR/$file"
#	echo "$_APPS_DIR/$file"
	sed -i "/$app $ver/d" "$_APPS"
#	echo "/$app $ver/d" "$_APPS"
}

for pkg in "$@"; do
	_app=($(awk "/$pkg/ { print \$2 }" "$_APPS"))
	_ver=($(awk "/$pkg/ { print \$3 }" "$_APPS"))

	if [[ "${#_app[@]}" -gt 1 ]]; then
		_echo "\nType wich version(s) of $pkg you want to remove separated by spaces:\n"
		for (( c=0; c<${#_ver[@]}; c++ )); do
			_echo "[$c] ${pkg}-${_ver[$c]}"
		done

		read -p " :: " -a user

		for a in "${user[@]}"; do
			app="$pkg"
			ver="${_ver[$a]}"
			file=($(awk "/$app $ver/ { print \$1 }" "$_APPS"))
			delete-pkg
		done
	else
		app="$pkg"
		ver="${_ver}"
		file=($(awk "/$app $ver/ { print \$1 }" "$_APPS"))
		delete-pkg
	fi
done

_echo "Done removing apps."
