#! /bin/bash

# Luis Lavaire 2017, @Nitrux S.A.

# The real locations could be this ones:
#
# 	${HOME}/.local/apps*
# 	/apps/*

export _APPS_DIR=".apps"				# Installation dir
export _DB="$_APPS_DIR/.nxdb"			# Packages database
export _APPS="$_APPS_DIR/.installed"	# Installed apps

_NXDB="https://raw.githubusercontent.com/Nitrux/nxs/master/nxdb"

_fail() { printf "\033[38;5;1m${@}\033[38;0;1m\n"; }
_echo() { printf "\033[38;5;5m${@}\033[38;0;1m\n"; }

_help() {
	_fail "USAGE: nxs [cmd] PKG"
	_echo "[cmd]: install | remove | update | find"
	exit
}

export -f _fail
export -f _echo
export -f _help


# - - - MAIN PROGRAM

mkdir -p "$_APPS_DIR"

[ -f "$_DB" ] || wget "$_NXDB" -qO "$_DB"

cmd=`tr [:upper:] [:lower:] <<< $1`

shift
case "$cmd" in
	"install")	./add $@;;
	"remove")	./del $@;;
	"find")		./fnd $@;;
	*)			_help;;
esac

echo
