#! /bin/sh

# Luis Lavaire 2017, @Nitrux S.A.

# nxs is a simple software installer designed to manage
# AppImage packages. When install is requested, it looks
# for the requested package in local database, and, if
# found, then it installs it (downloads) in 
# $HOME/.local/apps.
#
# When deletion is requested, it looks if the app exists
# in the apps directory and if so, it just deletes it.
#
# It can update all the packages installed to the latest
# version available also. List the ones installed or
# available for installation is supported too.
#
# Very easy, very funny. =D

# - - - 		CONFIG FILES

# ${HOME}/.apps

_DB=".apps/.nxdb"
_APPS_DIR=".apps"


# - - - 		FORMAT OUTPUT

_fail() { echo -e "\n - - \033[38;5;1m $@ \n"; }

_echo() { echo -e "\n - - \033[38;5;5m $@ \n"; }


# - - - 		MAIN FUNCTIONS

_help() { _echo "USAGE: nxs - [s] [r] [u] [l] PKG"; }

_add() {
	for pkg in "$@"; do
		target=`grep "$pkg" "$_DB" >/dev/null 2>&1`
		[ -z "$target" ] && { _echo "The name '$pkg' was not found in the database. Exiting"; exit; }
	done

	for pkg in "$@"; do
		target=`grep "$pkg" "$_DB" | awk '{ print $3 }'`
		app=`grep "$pkg" "$_DB" | awk '{ print $1 }'`
		wget $target -O "${_APPS_DIR}/${app}.ai"
	done
}

_del() {
	
}

_sy() {
	
}

_ls() {
	[ -z "$@" ] && { awk '{ print $1 }' "$_DB" | sort | uniq } || {
		
	}
}


# - - - 		PARSE COMMAND LINE

[ ! "$1" ] && _help

while getopts "i:r:u:l" cmd; do
	case "$cmd" in
		"i") _add $@;;
		"r") _del $@;;
		"u") _sy $OPTARG;;
		"l") _ls $OPTARG;;
		*) _help;;
	esac
done
