#! /bin/sh

# Luis Lavaire 2017, @Nitrux S.A.

# nxs is a simple software installer designed to manage
# AppImage packages. When install is requested, it looks
# for the requested package in local database, and, if
# found, then it installs it (downloads) in 
# $HOME/.local/apps.
#
# When deletion is requested, it looks if the app exists
# in the apps directory and if so, it just deletes it.
#
# It can update all the packages installed to the latest
# version available also. List the ones installed or
# available for installation is supported too.
#
# Very easy, very funny. =D


# - - - 		FORMAT OUTPUT

_fail() { printf "\v - - \033[38;5;1m $@ \v"; }

_fine() { printf "\v - - \033[38;5;5m $@ \v"; }


# - - - 		CONFIG FILES

_DB=".apps/.nxdb"

# - - - 		MAIN FUNCTIONS

_help() {
	_fine	"USAGE: nxs [ -s PKG ] [ -r PKG ] [ -u PKG ] [ -l ]\nyou must specify at least one argument"

	[ "$1" ] && _fine `cat << EOF
		
	`
	exit 1
}

_add() {
	for pkg in "$@"; do
		target=`grep "$pkg" "$_DB" | `
	done
}

_del() {
	echo del
}

_sy() {
	
}

_ls() {
	fineawk '{print $1}' "$_DB" | sort | uniq
}


# - - - 		PARSE COMMAND LINE

[ ! "$1" ] && _help

while getopts "i:r:u:l" cmd; do
	case "$cmd" in
		"i") _add $@;;
		"r") _del $@;;
		"u") _sy $OPTARG;;
		"l") _ls $OPTARG;;
		*) _help;;
	esac
done
